[theme]
base="light"
primaryColor="slateBlue"
backgroundColor="white"
secondaryBackgroundColor="lavender"
textColor="darkGoldenrod"
linkColor="darkOrchid"
codeBackgroundColor="lavender"
baseRadius="1rem"
buttonRadius="0.5rem"
borderColor="mediumSlateBlue"
showWidgetBorder=false

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"
primaryColor="darkGoldenrod"
baseRadius="0rem"
showWidgetBorder=true
